const en_US = {
    able:"Yes",
    administrator:"Administrators",
    add_cert:"Add Certificate",
    add_chaincode:"Add ChainCode",
    add_channel:"Add Channel",
    add_consortium:"Add Consortium",
    add_msp:"Add Msp",
    add_orderer:"Add Orderer",
    add_organization:"Add Organization",
    add_peer:"Add Peer",
    admin_msp:"Admin MSP",
    back:"Back",
    block_num:"Block Num",
    ca_common:"Certificate",
    ca_root:"Root Certificate",
    ca_tls_common:"TLS Certificate",
    ca_tls_root:"Root TLS Certificate",
    ca_type:"Certificate Type",
    certificate:"Certificate",
    chaincode:"ChainCode",
    chaincode_list:"ChainCode List",
    chaincode_manage:"Chaincodes",
    chaincode_name:"ChainCode Name",
    channel:"Channels",
    channel_desc:"Channel Description",
    channel_list:"Channel List",
    channel_manage:"Channels",
    channel_name:"Channel Name",
    chaincode_port:"ChainCode Port",
    common_name:"Common Name",
    console_panel:"Console Panel",
    consortium_desc:"Consortium Description",
    consortium_manage:"Consortiums",
    consortium_msps:"Consortium Msp",
    consortium_name:"Consortium Name",
    consortium_type:"Consortium Type",
    consortium:"Consortium",
    consortiums:"Consortiums",
    country:"Country",
    delete:"Delete",
    desc_1:"Oldest:-2 Newest:-1 Specify:>=0",
    desc_2:"Please create peer node of {param1} first",
    desc_3:"Please run orderer node first:【{param1}】",
    desc_4:"Please run peer node first:【{param1}】",
    desc_5:"Fail to enble the channel,please check :1 whether the node has been run according to the order. 2 whether already exists a channel with the same name.",
    desc_6:"1 Organizations Manage,MSPs Auto Create,Certificates Manage,Consortiums Manage,Channels Manage.",
    desc_7:"2 Add ChainCode,Enable Chaincode,Stop Chaincode.",
    desc_8:"3 Orderers Manage,Run Orderer,Stop Orderer,View Block.",
    desc_9:"4 Peers Manage, Run Peer, Stop Peer, List Channel, Join Channel, Get Channel Info, Install ChainCode, List ChainCode, Init ChainCode, Invoke ChainCode, Query Chaincode.",
    desc_10:"Functionalities",
    desc_11:"3 Cross-platform for windows,liunx,mac.",
    desc_12:"2 User friendly building environment, docker container not needed. Single machine mode only.",
    desc_13:"1 Essential tool for you to start learning hyperledger fabric.",
    desc_14:"Introduction",
    desc_15:"Simple Hyperledger Fabric Manage Tool",
    disable:"No",
    enabled:"Enabled",
    enable_channel:"Enabled",
    event_port:"Event Port",
    get_channel_info:"Get Channel Info",
    ip_address:"IP Address",
    is_tls:"TLS Certificate",
    init_code:"Init Code",
    init_chaincode:"Init ChainCode",
    install_chaincode:"Install ChainCode",
    intermediate_ca:"Intermediate CAs",
    invoke_chaincode:"Invoke ChainCode",
    invoke_code:"Invoke Code",
    is_enable:"",
    join_channel:"Join Channel",
    key:"Key",
    keys:"Keys",
    ledger_type:"Ledger Type",
    language:"Language",
    locality:"Locality",
    log:"Log",
    msp_id:"MSP ID",
    msp_name:"MSP Name",
    msp_level:"MSP Level",
    no:"No",
    name:"Name",
    node_already_run:"Node has been run",
    node_already_stop:"Node has been stopped",
    node_identity:"Node Identity",
    node_stop_ok:"Success Stop",
    node_must_run:"Current node must run first",
    node_name:"Node Name",
    node_type:"Node Type",
    operation:"Operation",
    organization:"Organization",
    organizations:"Organizations",
    organization_manage:"Organizations",
    organization_unit:"Organization Units",
    orderer_manage:"Orderers",
    orderer_name:"Orderer Name",
    parent_ca:"Parent Certificate (Empty option is self-signed)",
    path:"Path",
    peer_manage:"Peers",
    peer_msp:"Peer Msp",
    peer_name:"Peer Name",
    peers:"Peers",
    port:"Port",
    province:"Province",
    query_chaincode:"Query ChainCode",
    query_code:"Query Code",
    revoked_ca:"Revoked Certificates",
    role:"Role",
    root_ca:"Root CAs",
    run_chaincode:"Run ChainCode",
    run_cmd:"Run Cmd",
    run_node:"Run Node",
    running:"running....",
    stop:"not running...",
    stop_chaincode:"Stop ChainCode",
    stop_node:"Stop Node",
    submit:"Submit",
    tls_intermediate_ca:"TLS Intermediate CA",
    tls_root_ca:"TLS Root CA",
    version:"Version",
    view:"View",
    view_block:"View Block",
    yes:"Yes",
}
export default en_US;