const en_US = {
    able:"Yes",
    add_chaincode:"Add ChainCode",
    add_channel:"Add Channel",
    add_consortium:"Add Consortium",
    add_orderer:"Add Orderer",
    add_organization:"Add Organization",
    add_peer:"Add Peer",
    admin_msp:"Admin MSP",
    back:"Back",
    block_num:"Block Num",
    certificate:"Certificate",
    channel_desc:"Channel Description",
    chaincode:"ChainCode",
    chaincode_manage:"Chaincodes",
    chaincode_name:"ChainCode Name",
    channel_manage:"Channels",
    channel_name:"Channel Name",
    chaincode_port:"ChainCode Port",
    common_name:"Common Name",
    console_panel:"Console Panel",
    consortium_desc:"Consortium Description",
    consortium_manage:"Consortiums",
    consortium_msps:"Consortium Msp",
    consortium_name:"Consortium Name",
    consortium_type:"Consortium Type",
    consortium:"Consortium",
    consortiums:"Consortiums",
    country:"Country",
    delete:"Delete",
    desc_1:"Oldest:-2 Newest:-1 Specify:>=0",
    disable:"No",
    enabled:"Enabled",
    enable_channel:"Enabled",
    event_port:"Event Port",
    ip_address:"IP Address",
    init_code:"Init Code",
    invoke_code:"Invoke Code",
    is_enable:"",
    keys:"Keys",
    ledger_type:"Ledger Type",
    language:"Language",
    locality:"Locality",
    log:"Log",
    msp_id:"MSP ID",
    msp_name:"MSP Name",
    name:"Name",
    node_already_run:"Node already run",
    node_already_stop:"Node already stop",
    node_stop_ok:"Success Stop",
    node_must_run:"Current node must run first",
    node_name:"Node Name",
    node_type:"Node Type",
    operation:"Operation",
    organization:"Organization",
    organizations:"Organizations",
    organization_manage:"Organizations",
    orderer_manage:"Orderers",
    orderer_name:"Orderer Name",
    path:"Path",
    peer_manage:"Peers",
    peer_msp:"Peer Msp",
    peer_name:"Peer Name",
    peers:"Peers",
    port:"Port",
    province:"Province",
    query_code:"Query Code",
    role:"Role",
    run_chaincode:"Run ChainCode",
    run_cmd:"Run Cmd",
    run_node:"Run Node",
    running:"running....",
    stop_chaincode:"Stop ChainCode",
    stop_node:"Stop Node",
    submit:"Submit",
    version:"Version",
    view:"View",
    view_block:"View Block",
}
export default en_US;