const zh_CN = {
    able:"已启用",
    administrator:"管理员",
    add_cert:"添加证书",
    add_chaincode:"添加链码",
    add_channel:"添加通道",
    add_consortium:"添加联盟",
    add_msp:"添加MSP",
    add_orderer:"添加Orderer",
    add_organization:"添加组织",
    add_peer:"添加Peer",
    admin_msp:"管理员MSP",
    back:"返回",
    block_num:"区块数",
    ca_common:"证书",
    ca_root:"根证书",
    ca_tls_common:"TLS 证书",
    ca_tls_root:"Root TLS 根证书",
    ca_type:"证书类型",
    certificate:"证书",
    chaincode:"链码",
    chaincode_list:"链码清单",
    chaincode_manage:"链码管理",
    chaincode_name:"链码名称",
    channel:"通道",
    channel_desc:"通道描述",
    channel_list:"通道清单",
    channel_manage:"通道管理",
    channel_name:"通道名称",
    chaincode_port:"ChainCode端口",
    common_name:"公用名称",
    console_panel:"控制台",
    consortium_desc:"联盟描述",
    consortium_manage:"联盟管理",
    consortium_msps:"联盟MSP",
    consortium_name:"联盟名称",
    consortium_type:"联盟类型",
    consortium:"联盟",
    consortiums:"联盟",
    country:"国家",
    delete:"删除",
    desc_1:"最旧区块:-2 最新区块:-1 指定区块数:>=0",
    desc_2:"请先添加组织【{param1}】的Peer节点",
    desc_3:"请先启动orderer节点:【{param1}】",
    desc_4:"请先启动peer节点:【{param1}】",
    desc_5:"启用通道失败，请确认 1.对应Order节点是否已经启动。 2.已经存在同名通道",
    desc_6:"1 组织管理 MSP管理 证书管理 联盟管理 通道管理",
    desc_7:"2 链码管理 添加链码 启动链码 停止链码",
    desc_8:"3 Orderer管理 启动节点 停止节点 查看区块",
    desc_9:"4 Peer管理 启动节点 停止节点 通道清单 加入通道 获取通道信息 安装链码 链码清单 初始化链码 调用链码 查询链码",
    desc_10:"当前功能",
    desc_11:"3 多平台支持 windows,liunx,mac",
    desc_12:"2 轻松搭建环境,无需使用docker容器。目前仅支持单机环境。",
    desc_13:"1 学习超级账本(hyperledger fabric) 入门必备工具。",
    desc_14:"项目简介",
    desc_15:"超级账本管理端",
    disable:"未启用",
    enabled:"是否启用",
    enable_channel:"启用通道",
    event_port:"Event端口",
    get_channel_info:"获取通道信息",
    ip_address:"IP地址",
    is_tls:"TLS证书",
    init_chaincode:"初始化链码",
    init_code:"初始化语句",
    install_chaincode:"Install Chaincode",
    intermediate_ca:"中级证书",
    invoke_chaincode:"调用链码",
    invoke_code:"调用语句",
    is_enable:"是否启用",
    join_channel:"加入通道",
    key:"密钥",
    keys:"密钥",
    ledger_type:"账本类型",
    language:"语言",
    locality:"城市",
    log:"日志",
    msp_id:"MSP ID",
    msp_name:"MSP名称",
    name:"名称",
    no:"否",
    node_already_run:"节点已经启动",
    node_already_stop:"节点已经停止",
    node_identity:"节点身份证书",
    node_stop_ok:"节点停止成功",
    node_must_run:"请先启动当前节点",
    node_name:"节点名称",
    node_type:"节点类型",
    operation:"操作",
    organization:"单位名称",
    organizations:"组织",
    organization_manage:"组织管理",
    organization_unit:"组织单元",
    orderer_manage:"Orderer节点",
    orderer_name:"Orderer名称",
    parent_ca:"父证书 (空选项表示使用自签名)",
    path:"路径",
    peer_manage:"Peer节点",
    peer_msp:"Peer Msp",
    peer_name:"Peer名称",
    peers:"Peer 节点",
    port:"端口",
    province:"省份",
    query_chaincode:"查询链码",
    query_code:"查询语句",
    revoked_ca:"吊销证书列表",
    role:"角色",
    root_ca:"根证书",
    run_chaincode:"运行链码",
    run_cmd:"执行命令",
    run_node:"启动节点",
    running:"运行中....",
    stop:"未运行",
    stop_chaincode:"停止链码",
    stop_node:"停止节点",
    submit:"提交",
    tls_intermediate_ca:"TLS 中级证书",
    tls_root_ca:"TLS 跟证书",
    version:"版本",
    view:"查看",
    view_block:"查看区块",
    yes:"是",
}
export default zh_CN;